<!DOCTYPE html>
<html lang="en">
	<!-- container-fluid -->
	<head>
		<title>Fresh Sns Admin</title>
		
		<meta charset="UTF-8" />
		
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php 
        	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/_base/img/favicon.ico'));
        	
        	echo $this->Assets('css', array(
				'/static/css/bootstrap.min.css',
				'/static/css/bootstrap-responsive.min.css',
				'/static/css/fullcalendar.css',
				'/static/css/unicorn.main.css',
				'/static/css/unicorn.grey.css'
			));
		?>
        
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
	<body>
		
		
		<div id="header">
			<h1><a href="./dashboard.html">Fresh Sns Admin</a></h1>		
		</div>
		<div id="user-nav" class="navbar navbar-inverse">
            <ul class="nav btn-group">
                <li class="btn btn-inverse"><a title="" href="#"><i class="icon icon-user"></i> <span class="text">Profile</span></a></li>
                <li class="btn btn-inverse"><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
                <li class="btn btn-inverse"><a title="" href="login.html"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
            </ul>
        </div>
        
		<div id="sidebar">
			<a href="#" class="visible-phone">
			<?php echo $this->admin_navigation('AdminNavigation'); ?>
		</div>
		
		<div id="style-switcher">
			<i class="icon-arrow-left icon-white"></i>
			<span>Style:</span>
			<a href="#grey" style="background-color: #555555;border-color: #aaaaaa;"></a>
			<a href="#blue" style="background-color: #2D2F57;"></a>
			<a href="#red" style="background-color: #673232;"></a>
		</div>
		
		<div id="content">
			<div id="content-header">
				<h1>Dashboard</h1>
				<div class="btn-group">
					<a class="btn btn-large tip-bottom" title="Manage Files"><i class="icon-file"></i></a>
					<a class="btn btn-large tip-bottom" title="Manage Users"><i class="icon-user"></i></a>
					<a class="btn btn-large tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a>
					<a class="btn btn-large tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a>
				</div>
			</div>
			<div id="breadcrumb">
				<a href="#" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a>
				<a href="#" class="current">Dashboard</a>
			</div>
			<div class="container-fluid">
				<?php echo $this->content; ?>
				<div class="row-fluid">
					<div id="footer" class="span12">
						2012 &copy; Unicorn Admin. Brought to you by <a href="https://wrapbootstrap.com/user/diablo9983">diablo9983</a>
					</div>
				</div>
			</div>
		</div>
		
		<!-- Scripts -->
		<?php	
			echo $this->Assets('js', array(
				'/static/js/excanvas.min.js',
				'/static/js/jquery.min.js',
				'/static/js/jquery.ui.custom.js',
				'/static/js/bootstrap.min.js',
				'/static/js/jquery.flot.min.js',
				'/static/js/jquery.flot.resize.min.js',
				'/static/js/jquery.peity.min.js',
				'/static/js/fullcalendar.min.js',
				'/static/js/unicorn.js',
				'/static/js/unicorn.dashboard.js',
			));
        ?>
	</body>
</html>
