<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('欢迎来到 %sFresh SNS%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Fresh项目遵循的理念，开放的标准，开放式的设计，开放式的开发和开放式管理。Fresh是作为一个孵化性质的微博客开源项目，旨在为用户提供一个快捷方便的本地化垂直型社区解决方案。'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
</div>

<div class="row">
    <div class="span10">
        <h2><?php echo $this->translate('开发动态:') ?></h2>
        <p><?php echo sprintf($this->translate('%s2013/08/30%s 正式立项。 框架搭建, 进行需求分析和数据库设计。'), '<span class="zf-green">', '</span>'); ?></p>
    </div>
</div>