<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return \Zend\Stdlib\ArrayUtils::merge(array(
    'modules' => array(
    	// Core
    	'Core',
    	'Backend',
        'Application',
    	'User',
    	'Rbac',
    	'AsseticBundle',
    	'BjyProfiler',
    	'ZendDeveloperTools',
    ),
    'module_listener_options' => array(
        'config_glob_paths' => array(
        	'./config/autoload/{,*.}{global,local}.php',
        	'./config/autoload/environments/develop/{,*.}{global,local}.php'
        )
    ),
), include __DIR__.'/application.config.php');