<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
	'modules' => array(
		// Vendor Module
		'AsseticBundle',
		'DoctrineModule',
		'DoctrineORMModule',
		'DoctrineDataFixtureModule',
		
		// Core Module
        'Application',
		'Core',
    	'Admin',
    	'Rbac',
		'User',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './core/module',
        	'./apps',
        ),
    ),
	'service_manager' => array(
		'factories'    => array(
			'ServiceListener' => 'Fresh\Mvc\Service\ServiceListenerFactory',
		),
	),
);