<?php
$stringKey = 'test';
$isEnabled = true;

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return \Zend\Stdlib\ArrayUtils::merge(array(
    'modules' => array(
    ),
    'module_listener_options' => array(
        'config_glob_paths' => array(
        	'./config/autoload/{,*.}{global,local}.php',
        	'./config/autoload/environments/production/{,*.}{global,local}.php'
        ),
        
        // Whether or not to enable a configuration cache.
        // If enabled, the merged configuration will be cached and used in
        // subsequent requests.
        'config_cache_enabled' => $isEnabled,

        // The key used to create the configuration cache file name.
        'config_cache_key' => $stringKey,

        // Whether or not to enable a module class map cache.
        // If enabled, creates a module class map cache which will be used
        // by in future requests, to reduce the autoloading process.
        'module_map_cache_enabled' => $isEnabled,

        // The key used to create the class map cache file name.
        'module_map_cache_key' => $stringKey,

        // The path in which to cache merged configuration.
        'cache_dir' => './data/cache/gloabl_config',

        // Whether or not to enable modules dependency checking.
        // Enabled by default, prevents usage of modules that depend on other modules
        // that weren't loaded.
        'check_dependencies' => $isEnabled,
    ),
    
), include __DIR__.'/global.application.config.php');